circuit_breaker:
  failure_threshold: 5
  cooldown: 30

health_check_interval_secs: 5
backends:
  - url: "http://127.0.0.1:4000"
  - url: "http://127.0.0.1:4001"
  - url: "http://127.0.0.1:4002"
  - url: "http://127.0.0.1:4003"
  - url: "http://127.0.0.1:4004"